*&---------------------------------------------------------------------*
*& Report ZDMS6_UPLOAD
*&---------------------------------------------------------------------*
*&
*&---------------------------------------------------------------------*
REPORT ZDMS1_UPLOAD.

TABLES: ZDMS1.

DATA: IT_DATA          TYPE STANDARD TABLE OF ZDMS1,
      WA_DATA          TYPE ZDMS1,
      IT_RAW           TYPE TRUXS_T_TEXT_DATA,
      LV_FILENAME      TYPE RLGRAP-FILENAME,
      LV_CLEANED_VALUE TYPE STRING.
DATA : IT_EXCEL TYPE TABLE OF ZALSMEX_TABLINE.
*DATA : wa_excel TYPE alsmex_tabline.

PARAMETERS: P_FILE TYPE RLGRAP-FILENAME OBLIGATORY.

AT SELECTION-SCREEN ON VALUE-REQUEST FOR P_FILE.
  CALL FUNCTION 'F4_FILENAME'
    EXPORTING
      PROGRAM_NAME  = SYST-CPROG
      DYNPRO_NUMBER = SYST-DYNNR
      FIELD_NAME    = ' '
    IMPORTING
      FILE_NAME     = P_FILE.

START-OF-SELECTION.
  LV_FILENAME  =  P_FILE.
  BREAK CTPLABAP.
*  CALL FUNCTION 'ALSM_EXCEL_TO_INTERNAL_TABLE'
  CALL FUNCTION 'ZALSM_EXCEL_TO_INTERNAL_TABLE'
    EXPORTING
      FILENAME                = LV_FILENAME
      I_BEGIN_COL             = '1'
      I_BEGIN_ROW             = '2'
      I_END_COL               = '999'
      I_END_ROW               = '99999'
    TABLES
      INTERN                  = IT_EXCEL
    EXCEPTIONS
      INCONSISTENT_PARAMETERS = 1
      UPLOAD_OLE              = 2
      OTHERS                  = 3.
  IF SY-SUBRC <> 0.
* Implement suitable error handling here
  ENDIF.

BREAK CTPLSK.
  LOOP AT IT_EXCEL INTO DATA(WA_EXCEL).
    CASE WA_EXCEL-COL.
      WHEN 1.
        WA_DATA-MJAHR =   WA_EXCEL-VALUE.
      WHEN 2.
        WA_DATA-MBLNR  = WA_EXCEL-VALUE.
        CALL FUNCTION 'CONVERSION_EXIT_ALPHA_INPUT'
          EXPORTING
            INPUT         =  WA_DATA-MBLNR
         IMPORTING
           OUTPUT        =  WA_DATA-MBLNR
                  .
      WHEN 3.
        WA_DATA-ZTYP = WA_EXCEL-VALUE  .
      WHEN 4.
        IF WA_EXCEL-VALUE IS NOT INITIAL.
          CONCATENATE WA_EXCEL-VALUE+6(4) WA_EXCEL-VALUE+3(2) WA_EXCEL-VALUE+0(2) INTO WA_EXCEL-VALUE .
          WA_DATA-BUDAT = WA_EXCEL-VALUE .
        ENDIF.

*        LV_CLEANED_VALUE = WA_EXCEL-VALUE.
*        REPLACE ALL OCCURRENCES OF '-' IN LV_CLEANED_VALUE WITH SPACE .
*        CONDENSE LV_CLEANED_VALUE.
*        WA_DATA-BUDAT  = LV_CLEANED_VALUE.
*        CLEAR LV_CLEANED_VALUE.
*        WA_DATA-BUDAT = WA_EXCEL-VALUE .
      WHEN 5.
        LV_CLEANED_VALUE = WA_EXCEL-VALUE.
        REPLACE ALL OCCURRENCES OF ':' IN LV_CLEANED_VALUE WITH SPACE .
        CONDENSE LV_CLEANED_VALUE.
        WA_DATA-UZEIT  = LV_CLEANED_VALUE.
        CLEAR LV_CLEANED_VALUE.
*        WA_DATA-UZEIT = WA_EXCEL-VALUE .
      WHEN 6.
        WA_DATA-UNAME = WA_EXCEL-VALUE .
      WHEN 7.
        WA_DATA-PERNR = WA_EXCEL-VALUE .
      WHEN 8.
        WA_DATA-WERKS  = WA_EXCEL-VALUE .
      WHEN 9.
        WA_DATA-D1 = WA_EXCEL-VALUE .
      WHEN 10.
        WA_DATA-D2 = WA_EXCEL-VALUE .
      WHEN 11.
        WA_DATA-D3 = WA_EXCEL-VALUE .
      WHEN 12.
        WA_DATA-D4 = WA_EXCEL-VALUE .
      WHEN 13.
        WA_DATA-D5 = WA_EXCEL-VALUE .
      WHEN 14.
        WA_DATA-D6 = WA_EXCEL-VALUE .
      WHEN 15.
        WA_DATA-D7 = WA_EXCEL-VALUE .
      WHEN 16.
        WA_DATA-D8 = WA_EXCEL-VALUE .
      WHEN 17.
        WA_DATA-D9 = WA_EXCEL-VALUE .
      WHEN 18.
        WA_DATA-D10 = WA_EXCEL-VALUE .
      WHEN 19.
        WA_DATA-D11 = WA_EXCEL-VALUE .
      WHEN 20.
        WA_DATA-D12 = WA_EXCEL-VALUE .
      WHEN 21.
        WA_DATA-DTEXT = WA_EXCEL-VALUE .
      WHEN 22.
        WA_DATA-ATEXT1 = WA_EXCEL-VALUE .
      WHEN 23.
        WA_DATA-ATEXT2 = WA_EXCEL-VALUE .
      WHEN 24.
        WA_DATA-ATEXT3 = WA_EXCEL-VALUE .
      WHEN 25.
        WA_DATA-ATEXT4 = WA_EXCEL-VALUE .
      WHEN 26.
        WA_DATA-ATEXT5 = WA_EXCEL-VALUE .
      WHEN 27.
        WA_DATA-BTEXT1 = WA_EXCEL-VALUE .
      WHEN 28.
        WA_DATA-BTEXT2 = WA_EXCEL-VALUE .
      WHEN 29.
        WA_DATA-BTEXT3 = WA_EXCEL-VALUE .
      WHEN 30.
        WA_DATA-BTEXT4 = WA_EXCEL-VALUE .
      WHEN 31.
        WA_DATA-BTEXT5 = WA_EXCEL-VALUE .
      WHEN 32.
        WA_DATA-CTEXT1 = WA_EXCEL-VALUE .
      WHEN 33.
        WA_DATA-CTEXT2 = WA_EXCEL-VALUE .
      WHEN 34.
        WA_DATA-CTEXT3 = WA_EXCEL-VALUE .
      WHEN 35.
        WA_DATA-CTEXT4 = WA_EXCEL-VALUE .
      WHEN 36.
        WA_DATA-CTEXT5 = WA_EXCEL-VALUE .
      WHEN 37.
        WA_DATA-DTEXT1 = WA_EXCEL-VALUE .
      WHEN 38.
        WA_DATA-DTEXT2 = WA_EXCEL-VALUE .
      WHEN 39.
        WA_DATA-DTEXT3 = WA_EXCEL-VALUE .
      WHEN 40.
        WA_DATA-DTEXT4 = WA_EXCEL-VALUE .
      WHEN 41.
        WA_DATA-DTEXT5 = WA_EXCEL-VALUE .
      WHEN 42.
        WA_DATA-ETEXT1 = WA_EXCEL-VALUE .
      WHEN 43.
        WA_DATA-ETEXT2 = WA_EXCEL-VALUE .
      WHEN 44.
        WA_DATA-ETEXT3 = WA_EXCEL-VALUE .
      WHEN 45.
        WA_DATA-ETEXT4 = WA_EXCEL-VALUE .
      WHEN 46.
        WA_DATA-ETEXT5 = WA_EXCEL-VALUE .
      WHEN 47.
        WA_DATA-FTEXT1 = WA_EXCEL-VALUE .
      WHEN 48.
        WA_DATA-FTEXT2 = WA_EXCEL-VALUE .
      WHEN 49.
        WA_DATA-FTEXT3 = WA_EXCEL-VALUE .
      WHEN 50.
        WA_DATA-FTEXT4 = WA_EXCEL-VALUE .
      WHEN 51.
        WA_DATA-FTEXT5 = WA_EXCEL-VALUE .
      WHEN 52.
        WA_DATA-APPROVE = WA_EXCEL-VALUE .
      WHEN 53.
        WA_DATA-REJECT = WA_EXCEL-VALUE .
      WHEN 54.
        WA_DATA-APERNR = WA_EXCEL-VALUE .
      WHEN 55.
        IF WA_EXCEL-VALUE IS NOT INITIAL.
          CONCATENATE WA_EXCEL-VALUE+6(4) WA_EXCEL-VALUE+3(2) WA_EXCEL-VALUE+0(2) INTO WA_EXCEL-VALUE .
          WA_DATA-ADATE = WA_EXCEL-VALUE .
        ENDIF.

*
*        LV_CLEANED_VALUE = WA_EXCEL-VALUE.
*        REPLACE ALL OCCURRENCES OF '-' IN LV_CLEANED_VALUE WITH SPACE .
*        CONDENSE LV_CLEANED_VALUE.
*        WA_DATA-ADATE  = LV_CLEANED_VALUE.
*        CLEAR LV_CLEANED_VALUE.
*        WA_DATA-ADATE = WA_EXCEL-VALUE .
      WHEN 56.
        LV_CLEANED_VALUE = WA_EXCEL-VALUE.
        REPLACE ALL OCCURRENCES OF ':' IN LV_CLEANED_VALUE WITH SPACE .
        CONDENSE LV_CLEANED_VALUE.
        WA_DATA-AUZEIT  = LV_CLEANED_VALUE.
        CLEAR LV_CLEANED_VALUE.
*        WA_DATA-AUZEIT = WA_EXCEL-VALUE .
      WHEN 57.
        WA_DATA-AUNAME = WA_EXCEL-VALUE .
      WHEN 58.
        WA_DATA-DREM1 = WA_EXCEL-VALUE .
      WHEN 59.
        WA_DATA-DREM2 = WA_EXCEL-VALUE .
      WHEN 60.
        WA_DATA-DREM3 = WA_EXCEL-VALUE .
      WHEN 61.
        WA_DATA-RAPPROVE1 = WA_EXCEL-VALUE .
      WHEN 62.
        WA_DATA-RREJECT1 = WA_EXCEL-VALUE .
      WHEN 63.
        WA_DATA-RPERNR = WA_EXCEL-VALUE .
      WHEN 64.
        IF WA_EXCEL-VALUE IS NOT INITIAL.
          CONCATENATE WA_EXCEL-VALUE+6(4) WA_EXCEL-VALUE+3(2) WA_EXCEL-VALUE+0(2) INTO WA_EXCEL-VALUE .
          WA_DATA-RDATE = WA_EXCEL-VALUE .
        ENDIF.

*        LV_CLEANED_VALUE = WA_EXCEL-VALUE.
*        REPLACE ALL OCCURRENCES OF '-' IN LV_CLEANED_VALUE WITH SPACE .
*        CONDENSE LV_CLEANED_VALUE.
*        WA_DATA-RDATE  = LV_CLEANED_VALUE.
*        CLEAR LV_CLEANED_VALUE.
*        WA_DATA-RDATE = WA_EXCEL-VALUE .
      WHEN 65.
        LV_CLEANED_VALUE = WA_EXCEL-VALUE.
        REPLACE ALL OCCURRENCES OF ':' IN LV_CLEANED_VALUE WITH SPACE .
        CONDENSE LV_CLEANED_VALUE.
        WA_DATA-RUZEIT  = LV_CLEANED_VALUE.
        CLEAR LV_CLEANED_VALUE.
*        WA_DATA-RUZEIT = WA_EXCEL-VALUE .
      WHEN 66.
        WA_DATA-RUNAME = WA_EXCEL-VALUE .
      WHEN 67.
        WA_DATA-RREM1 = WA_EXCEL-VALUE .
      WHEN 68.
        WA_DATA-RREM2 = WA_EXCEL-VALUE .
      WHEN 69.
        WA_DATA-RREM3 = WA_EXCEL-VALUE .
      WHEN 70.
        WA_DATA-RAPPROVE2 = WA_EXCEL-VALUE .
      WHEN 71.
        WA_DATA-RREJECT2 = WA_EXCEL-VALUE .
      WHEN 72.
        WA_DATA-RPERNR2 = WA_EXCEL-VALUE .
      WHEN 73.
         IF WA_EXCEL-VALUE IS NOT INITIAL.
          CONCATENATE WA_EXCEL-VALUE+6(4) WA_EXCEL-VALUE+3(2) WA_EXCEL-VALUE+0(2) INTO WA_EXCEL-VALUE .
          WA_DATA-RDATE2 = WA_EXCEL-VALUE .
        ENDIF.
*        LV_CLEANED_VALUE = WA_EXCEL-VALUE.
*        REPLACE ALL OCCURRENCES OF '-' IN LV_CLEANED_VALUE WITH SPACE .
*        CONDENSE LV_CLEANED_VALUE.
*        WA_DATA-RDATE2  = LV_CLEANED_VALUE.
*        CLEAR LV_CLEANED_VALUE.
*        WA_DATA-RDATE2 = WA_EXCEL-VALUE .
      WHEN 74.
        LV_CLEANED_VALUE = WA_EXCEL-VALUE.
        REPLACE ALL OCCURRENCES OF ':' IN LV_CLEANED_VALUE WITH SPACE .
        CONDENSE LV_CLEANED_VALUE.
        WA_DATA-RUZEIT2  = LV_CLEANED_VALUE.
        CLEAR LV_CLEANED_VALUE.
*        WA_DATA-RUZEIT2 = WA_EXCEL-VALUE .
      WHEN 75.
        WA_DATA-RUNAME2 = WA_EXCEL-VALUE .
      WHEN 76.
        WA_DATA-RREM21 = WA_EXCEL-VALUE .
      WHEN 77.
        WA_DATA-RREM22 = WA_EXCEL-VALUE .
      WHEN 78.
        WA_DATA-RREM23 = WA_EXCEL-VALUE .
      WHEN 79.
        WA_DATA-QAPPROVE1 = WA_EXCEL-VALUE .
      WHEN 80.
        WA_DATA-QREJECT1 = WA_EXCEL-VALUE .
      WHEN 81.
        WA_DATA-QPERNR1 = WA_EXCEL-VALUE .
      WHEN 82.
         IF WA_EXCEL-VALUE IS NOT INITIAL.
          CONCATENATE WA_EXCEL-VALUE+6(4) WA_EXCEL-VALUE+3(2) WA_EXCEL-VALUE+0(2) INTO WA_EXCEL-VALUE .
          WA_DATA-QDATE1 = WA_EXCEL-VALUE .
        ENDIF.
*        LV_CLEANED_VALUE = WA_EXCEL-VALUE.
*        REPLACE ALL OCCURRENCES OF '-' IN LV_CLEANED_VALUE WITH SPACE .
*        CONDENSE LV_CLEANED_VALUE.
*        WA_DATA-QDATE1  = LV_CLEANED_VALUE.
*        CLEAR LV_CLEANED_VALUE.
*        WA_DATA-QDATE1 = WA_EXCEL-VALUE .
      WHEN 83.
        LV_CLEANED_VALUE = WA_EXCEL-VALUE.
        REPLACE ALL OCCURRENCES OF ':' IN LV_CLEANED_VALUE WITH SPACE .
        CONDENSE LV_CLEANED_VALUE.
        WA_DATA-QUZEIT1  = LV_CLEANED_VALUE.
        CLEAR LV_CLEANED_VALUE.
*        WA_DATA-QUZEIT1 = WA_EXCEL-VALUE .
      WHEN 84.
        WA_DATA-QUNAME1 = WA_EXCEL-VALUE .
      WHEN 85.
        WA_DATA-QAREMARK1 = WA_EXCEL-VALUE .
      WHEN 86.
        WA_DATA-QAREMARK2 = WA_EXCEL-VALUE .
      WHEN 87.
        WA_DATA-QAREMARK3 = WA_EXCEL-VALUE .
      WHEN 88.
        WA_DATA-USELDEPT = WA_EXCEL-VALUE .
      WHEN 89.
         IF WA_EXCEL-VALUE IS NOT INITIAL.
          CONCATENATE WA_EXCEL-VALUE+6(4) WA_EXCEL-VALUE+3(2) WA_EXCEL-VALUE+0(2) INTO WA_EXCEL-VALUE .
          WA_DATA-DTSELDEPT = WA_EXCEL-VALUE .
        ENDIF.
*        LV_CLEANED_VALUE = WA_EXCEL-VALUE.
*        REPLACE ALL OCCURRENCES OF '-' IN LV_CLEANED_VALUE WITH SPACE .
*        CONDENSE LV_CLEANED_VALUE.
*        WA_DATA-DTSELDEPT  = LV_CLEANED_VALUE.
*        CLEAR LV_CLEANED_VALUE.
*        WA_DATA-DTSELDEPT = WA_EXCEL-VALUE .
      WHEN 90.
        LV_CLEANED_VALUE = WA_EXCEL-VALUE.
        REPLACE ALL OCCURRENCES OF ':' IN LV_CLEANED_VALUE WITH SPACE .
        CONDENSE LV_CLEANED_VALUE.
        WA_DATA-DTSELTM  = LV_CLEANED_VALUE.
        CLEAR LV_CLEANED_VALUE.
*        WA_DATA-DTSELTM = WA_EXCEL-VALUE .
      WHEN 91.
        WA_DATA-DTSELUNAME = WA_EXCEL-VALUE .
*      WHEN 91.
*        WA_DATA-BUDAT = WA_EXCEL-VALUE .

    ENDCASE.

    AT END OF ROW.
      WA_DATA-MANDT = SY-MANDT.
      APPEND WA_DATA TO IT_DATA .
      CLEAR : WA_DATA.
*      MODIFY zincvaldata FROM wa_data.
    ENDAT.

  ENDLOOP.
  MODIFY ZDMS1 FROM TABLE IT_DATA.
  IF SY-SUBRC  = 0.
    MESSAGE 'Upload finished. Data inserted/updated into ZDMS1.' TYPE 'S'.
    CLEAR WA_DATA.
    COMMIT WORK.
  ENDIF.
