*&---------------------------------------------------------------------*
*& Report ZDMS2_UPLOAD
*&---------------------------------------------------------------------*
*&
*&---------------------------------------------------------------------*
REPORT ZDMS2_UPLOAD_NEW.

TABLES: ZDMS2.

DATA: IT_DATA          TYPE STANDARD TABLE OF ZDMS2,
      WA_DATA          TYPE ZDMS2,
      IT_RAW           TYPE TRUXS_T_TEXT_DATA,
      LV_FILENAME      TYPE RLGRAP-FILENAME,
      LV_CLEANED_VALUE TYPE STRING.
*DATA : IT_EXCEL TYPE TABLE OF ALSMEX_TABLINE.
DATA : IT_EXCEL TYPE TABLE OF ZALSMEX_TABLINE.
*DATA : wa_excel TYPE alsmex_tabline.

PARAMETERS: P_FILE TYPE RLGRAP-FILENAME OBLIGATORY.

AT SELECTION-SCREEN ON VALUE-REQUEST FOR P_FILE.
  CALL FUNCTION 'F4_FILENAME'
    EXPORTING
      PROGRAM_NAME  = SYST-CPROG
      DYNPRO_NUMBER = SYST-DYNNR
      FIELD_NAME    = ' '
    IMPORTING
      FILE_NAME     = P_FILE.

START-OF-SELECTION.
  LV_FILENAME  =  P_FILE.
  BREAK CTPLABAP.
*  CALL FUNCTION 'ALSM_EXCEL_TO_INTERNAL_TABLE'
  CALL FUNCTION 'ZALSM_EXCEL_TO_INTERNAL_TABLE'
    EXPORTING
      FILENAME                = LV_FILENAME
      I_BEGIN_COL             = '1'
      I_BEGIN_ROW             = '2'
      I_END_COL               = '99'
      I_END_ROW               = '99999'
    TABLES
      INTERN                  = IT_EXCEL
    EXCEPTIONS
      INCONSISTENT_PARAMETERS = 1
      UPLOAD_OLE              = 2
      OTHERS                  = 3.
  IF SY-SUBRC <> 0.
* Implement suitable error handling here
  ENDIF.


  LOOP AT IT_EXCEL INTO DATA(WA_EXCEL).
    CASE WA_EXCEL-COL.
      WHEN 1.
        WA_DATA-MJAHR =   WA_EXCEL-VALUE.
      WHEN 2.
        WA_DATA-MBLNR  = WA_EXCEL-VALUE.
        CALL FUNCTION 'CONVERSION_EXIT_ALPHA_INPUT'
          EXPORTING
            INPUT         =  WA_DATA-MBLNR
         IMPORTING
           OUTPUT        =  WA_DATA-MBLNR
                  .
      WHEN 3.
        WA_DATA-DEPT = WA_EXCEL-VALUE  .
      WHEN 4.
        IF WA_EXCEL-VALUE IS NOT INITIAL.
          CONCATENATE WA_EXCEL-VALUE+6(4) WA_EXCEL-VALUE+3(2) WA_EXCEL-VALUE+0(2) INTO WA_EXCEL-VALUE .
          WA_DATA-EBUDAT = WA_EXCEL-VALUE .
        ENDIF.
*        WA_DATA-EBUDAT = WA_EXCEL-VALUE .
      WHEN 5.
         LV_CLEANED_VALUE = WA_EXCEL-VALUE.
        REPLACE ALL OCCURRENCES OF ':' IN LV_CLEANED_VALUE WITH SPACE .
        CONDENSE LV_CLEANED_VALUE.
        WA_DATA-EUZEIT  = LV_CLEANED_VALUE.
        CLEAR LV_CLEANED_VALUE.
*        WA_DATA-EUZEIT = WA_EXCEL-VALUE .
      WHEN 6.
        WA_DATA-EUNAME = WA_EXCEL-VALUE .
      WHEN 7.
        WA_DATA-EPERNR = WA_EXCEL-VALUE .
      WHEN 8.
         IF WA_EXCEL-VALUE IS NOT INITIAL.
          CONCATENATE WA_EXCEL-VALUE+6(4) WA_EXCEL-VALUE+3(2) WA_EXCEL-VALUE+0(2) INTO WA_EXCEL-VALUE .
          WA_DATA-UBUDAT = WA_EXCEL-VALUE .
        ENDIF.
*        WA_DATA-UBUDAT = WA_EXCEL-VALUE .
      WHEN 9.
         LV_CLEANED_VALUE = WA_EXCEL-VALUE.
        REPLACE ALL OCCURRENCES OF ':' IN LV_CLEANED_VALUE WITH SPACE .
        CONDENSE LV_CLEANED_VALUE.
        WA_DATA-UZEIT  = LV_CLEANED_VALUE.
        CLEAR LV_CLEANED_VALUE.
*        WA_DATA-UZEIT = WA_EXCEL-VALUE .
      WHEN 10.
        WA_DATA-UNAME = WA_EXCEL-VALUE .
      WHEN 11.
        WA_DATA-UPERNR = WA_EXCEL-VALUE .
      WHEN 12.
        WA_DATA-APPROVE = WA_EXCEL-VALUE .
      WHEN 13.
        WA_DATA-REJECT = WA_EXCEL-VALUE .
      WHEN 14.
        WA_DATA-NA = WA_EXCEL-VALUE .
      WHEN 15.
        WA_DATA-NATEXT = WA_EXCEL-VALUE .
      WHEN 16.
        WA_DATA-ATEXT1 = WA_EXCEL-VALUE .
      WHEN 17.
         IF WA_EXCEL-VALUE IS NOT INITIAL.
          CONCATENATE WA_EXCEL-VALUE+6(4) WA_EXCEL-VALUE+3(2) WA_EXCEL-VALUE+0(2) INTO WA_EXCEL-VALUE .
          WA_DATA-TDATE1 = WA_EXCEL-VALUE .
        ENDIF.
*        WA_DATA-TDATE1 = WA_EXCEL-VALUE .
      WHEN 18.
         IF WA_EXCEL-VALUE IS NOT INITIAL.
          CONCATENATE WA_EXCEL-VALUE+6(4) WA_EXCEL-VALUE+3(2) WA_EXCEL-VALUE+0(2) INTO WA_EXCEL-VALUE .
          WA_DATA-CTDATE1 = WA_EXCEL-VALUE .
        ENDIF.
*        WA_DATA-CTDATE1 = WA_EXCEL-VALUE .
      WHEN 19.
        WA_DATA-REM1 = WA_EXCEL-VALUE .
      WHEN 20.
        IF WA_EXCEL-VALUE IS NOT INITIAL.
          CONCATENATE WA_EXCEL-VALUE+6(4) WA_EXCEL-VALUE+3(2) WA_EXCEL-VALUE+0(2) INTO WA_EXCEL-VALUE .
          WA_DATA-CTDT1ON = WA_EXCEL-VALUE .
        ENDIF.
*        WA_DATA-CTDT1ON = WA_EXCEL-VALUE .
      WHEN 21.
        WA_DATA-ATEXT2 = WA_EXCEL-VALUE .
      WHEN 22.
         IF WA_EXCEL-VALUE IS NOT INITIAL.
          CONCATENATE WA_EXCEL-VALUE+6(4) WA_EXCEL-VALUE+3(2) WA_EXCEL-VALUE+0(2) INTO WA_EXCEL-VALUE .
          WA_DATA-TDATE2 = WA_EXCEL-VALUE .
        ENDIF.
*        WA_DATA-TDATE2 = WA_EXCEL-VALUE .
      WHEN 23.
         IF WA_EXCEL-VALUE IS NOT INITIAL.
          CONCATENATE WA_EXCEL-VALUE+6(4) WA_EXCEL-VALUE+3(2) WA_EXCEL-VALUE+0(2) INTO WA_EXCEL-VALUE .
          WA_DATA-CTDATE2 = WA_EXCEL-VALUE .
        ENDIF.
*        WA_DATA-CTDATE2 = WA_EXCEL-VALUE .
      WHEN 24.
        WA_DATA-REM2 = WA_EXCEL-VALUE .
      WHEN 25.
        IF WA_EXCEL-VALUE IS NOT INITIAL.
          CONCATENATE WA_EXCEL-VALUE+6(4) WA_EXCEL-VALUE+3(2) WA_EXCEL-VALUE+0(2) INTO WA_EXCEL-VALUE .
          WA_DATA-CTDT2ON = WA_EXCEL-VALUE .
        ENDIF.
        WA_DATA-CTDT2ON = WA_EXCEL-VALUE .
      WHEN 26.
        WA_DATA-ATEXT3 = WA_EXCEL-VALUE .
      WHEN 27.
         IF WA_EXCEL-VALUE IS NOT INITIAL.
          CONCATENATE WA_EXCEL-VALUE+6(4) WA_EXCEL-VALUE+3(2) WA_EXCEL-VALUE+0(2) INTO WA_EXCEL-VALUE .
          WA_DATA-TDATE3 = WA_EXCEL-VALUE .
        ENDIF.
*        WA_DATA-TDATE3 = WA_EXCEL-VALUE .
      WHEN 28.
         IF WA_EXCEL-VALUE IS NOT INITIAL.
          CONCATENATE WA_EXCEL-VALUE+6(4) WA_EXCEL-VALUE+3(2) WA_EXCEL-VALUE+0(2) INTO WA_EXCEL-VALUE .
          WA_DATA-CTDATE3 = WA_EXCEL-VALUE .
        ENDIF.
*        WA_DATA-CTDATE3 = WA_EXCEL-VALUE .
      WHEN 29.
        WA_DATA-REM3 = WA_EXCEL-VALUE .
      WHEN 30.
        IF WA_EXCEL-VALUE IS NOT INITIAL.
          CONCATENATE WA_EXCEL-VALUE+6(4) WA_EXCEL-VALUE+3(2) WA_EXCEL-VALUE+0(2) INTO WA_EXCEL-VALUE .
          WA_DATA-CTDT3ON = WA_EXCEL-VALUE .
        ENDIF.
*        WA_DATA-CTDT3ON = WA_EXCEL-VALUE .
      WHEN 31.
        WA_DATA-ATEXT4 = WA_EXCEL-VALUE .
      WHEN 32.
         IF WA_EXCEL-VALUE IS NOT INITIAL.
          CONCATENATE WA_EXCEL-VALUE+6(4) WA_EXCEL-VALUE+3(2) WA_EXCEL-VALUE+0(2) INTO WA_EXCEL-VALUE .
          WA_DATA-TDATE4 = WA_EXCEL-VALUE .
        ENDIF.
*        WA_DATA-TDATE4 = WA_EXCEL-VALUE .
      WHEN 33.
         IF WA_EXCEL-VALUE IS NOT INITIAL.
          CONCATENATE WA_EXCEL-VALUE+6(4) WA_EXCEL-VALUE+3(2) WA_EXCEL-VALUE+0(2) INTO WA_EXCEL-VALUE .
          WA_DATA-CTDATE4 = WA_EXCEL-VALUE .
        ENDIF.
*        WA_DATA-CTDATE4 = WA_EXCEL-VALUE .
      WHEN 34.
        WA_DATA-REM4 = WA_EXCEL-VALUE .
      WHEN 35.
          IF WA_EXCEL-VALUE IS NOT INITIAL.
          CONCATENATE WA_EXCEL-VALUE+6(4) WA_EXCEL-VALUE+3(2) WA_EXCEL-VALUE+0(2) INTO WA_EXCEL-VALUE .
          WA_DATA-CTDT4ON = WA_EXCEL-VALUE .
        ENDIF.
*        WA_DATA-CTDT4ON = WA_EXCEL-VALUE .
      WHEN 36.
        WA_DATA-ATEXT5 = WA_EXCEL-VALUE .
      WHEN 37.
          IF WA_EXCEL-VALUE IS NOT INITIAL.
          CONCATENATE WA_EXCEL-VALUE+6(4) WA_EXCEL-VALUE+3(2) WA_EXCEL-VALUE+0(2) INTO WA_EXCEL-VALUE .
          WA_DATA-TDATE5 = WA_EXCEL-VALUE .
        ENDIF.
*        WA_DATA-TDATE5 = WA_EXCEL-VALUE .
      WHEN 38.
         IF WA_EXCEL-VALUE IS NOT INITIAL.
          CONCATENATE WA_EXCEL-VALUE+6(4) WA_EXCEL-VALUE+3(2) WA_EXCEL-VALUE+0(2) INTO WA_EXCEL-VALUE .
          WA_DATA-CTDATE5 = WA_EXCEL-VALUE .
        ENDIF.
*        WA_DATA-CTDATE5 = WA_EXCEL-VALUE .
      WHEN 39.
        WA_DATA-REM5 = WA_EXCEL-VALUE .
      WHEN 40.
         IF WA_EXCEL-VALUE IS NOT INITIAL.
          CONCATENATE WA_EXCEL-VALUE+6(4) WA_EXCEL-VALUE+3(2) WA_EXCEL-VALUE+0(2) INTO WA_EXCEL-VALUE .
          WA_DATA-CTDT5ON = WA_EXCEL-VALUE .
        ENDIF.
*        WA_DATA-CTDT5ON = WA_EXCEL-VALUE .



    ENDCASE.

    AT END OF ROW.
      WA_DATA-MANDT = SY-MANDT.
      APPEND WA_DATA TO IT_DATA .
*      MODIFY zincvaldata FROM wa_data.
      CLEAR : WA_DATA.
    ENDAT.

  ENDLOOP.
  MODIFY ZDMS2 FROM TABLE IT_DATA.
  IF SY-SUBRC  = 0.
    MESSAGE 'Upload finished. Data inserted/updated into ZDMS2.' TYPE 'S'.
    CLEAR WA_DATA.
    COMMIT WORK.
  ENDIF.
