*&---------------------------------------------------------------------*
*& Report ZDMS5_UPLOAD
*&---------------------------------------------------------------------*
*&
*&---------------------------------------------------------------------*
REPORT ZDMS5_UPLOAD.

TABLES: ZDMS5.

DATA: IT_DATA          TYPE STANDARD TABLE OF ZDMS5,
      WA_DATA          TYPE ZDMS5,
      IT_RAW           TYPE TRUXS_T_TEXT_DATA,
      LV_FILENAME      TYPE RLGRAP-FILENAME,
      LV_CLEANED_VALUE TYPE STRING.
DATA : IT_EXCEL TYPE TABLE OF ZALSMEX_TABLINE.
*DATA : wa_excel TYPE alsmex_tabline.

PARAMETERS: P_FILE TYPE RLGRAP-FILENAME OBLIGATORY.

AT SELECTION-SCREEN ON VALUE-REQUEST FOR P_FILE.
  CALL FUNCTION 'F4_FILENAME'
    EXPORTING
      PROGRAM_NAME  = SYST-CPROG
      DYNPRO_NUMBER = SYST-DYNNR
      FIELD_NAME    = ' '
    IMPORTING
      FILE_NAME     = P_FILE.

START-OF-SELECTION.
  LV_FILENAME  =  P_FILE.
  BREAK CTPLABAP.
  CALL FUNCTION 'ZALSM_EXCEL_TO_INTERNAL_TABLE'
    EXPORTING
      FILENAME                = LV_FILENAME
      I_BEGIN_COL             = '1'
      I_BEGIN_ROW             = '2'
      I_END_COL               = '99'
      I_END_ROW               = '99999'
    TABLES
      INTERN                  = IT_EXCEL
    EXCEPTIONS
      INCONSISTENT_PARAMETERS = 1
      UPLOAD_OLE              = 2
      OTHERS                  = 3.
  IF SY-SUBRC <> 0.
* Implement suitable error handling here
  ENDIF.


  LOOP AT IT_EXCEL INTO DATA(WA_EXCEL).
    CASE WA_EXCEL-COL.
      WHEN 1.
        WA_DATA-MJAHR =   WA_EXCEL-VALUE.
      WHEN 2.
        WA_DATA-MBLNR  = WA_EXCEL-VALUE.
        CALL FUNCTION 'CONVERSION_EXIT_ALPHA_INPUT'
          EXPORTING
            INPUT         =  WA_DATA-MBLNR
         IMPORTING
           OUTPUT        =  WA_DATA-MBLNR
                  .
      WHEN 3.
        WA_DATA-EIPERNR = WA_EXCEL-VALUE  .
      WHEN 4.
         IF WA_EXCEL-VALUE IS NOT INITIAL.
          CONCATENATE WA_EXCEL-VALUE+6(4) WA_EXCEL-VALUE+3(2) WA_EXCEL-VALUE+0(2) INTO WA_EXCEL-VALUE .
          WA_DATA-EIDATE = WA_EXCEL-VALUE .
        ENDIF.
*         LV_CLEANED_VALUE = WA_EXCEL-VALUE.
*        REPLACE ALL OCCURRENCES OF '-' IN LV_CLEANED_VALUE WITH SPACE .
*        CONDENSE LV_CLEANED_VALUE.
*        WA_DATA-EIDATE  = LV_CLEANED_VALUE.
*        CLEAR LV_CLEANED_VALUE.
*        WA_DATA-EIDATE = WA_EXCEL-VALUE .
      WHEN 5.
         LV_CLEANED_VALUE = WA_EXCEL-VALUE.
        REPLACE ALL OCCURRENCES OF ':' IN LV_CLEANED_VALUE WITH SPACE .
        CONDENSE LV_CLEANED_VALUE.
        WA_DATA-EIUZEIT  = LV_CLEANED_VALUE.
        CLEAR LV_CLEANED_VALUE.
*        WA_DATA-EIUZEIT = WA_EXCEL-VALUE .
      WHEN 6.
        WA_DATA-EIUNAME = WA_EXCEL-VALUE .
      WHEN 7.
        WA_DATA-EIDAYS = WA_EXCEL-VALUE .
      WHEN 8.
        WA_DATA-RTEXT1 = WA_EXCEL-VALUE .
      WHEN 9.
        WA_DATA-RTEXT2 = WA_EXCEL-VALUE .
      WHEN 10.
        WA_DATA-RTEXT3 = WA_EXCEL-VALUE .
      WHEN 11.
        WA_DATA-RTEXT4 = WA_EXCEL-VALUE .
      WHEN 12.
        WA_DATA-RTEXT5 = WA_EXCEL-VALUE .
      WHEN 13.
        WA_DATA-RTEXT6 = WA_EXCEL-VALUE .
      WHEN 14.
        WA_DATA-RTEXT7 = WA_EXCEL-VALUE .
      WHEN 15.
        WA_DATA-RTEXT8 = WA_EXCEL-VALUE .
      WHEN 16.
        WA_DATA-RTEXT9 = WA_EXCEL-VALUE .
      WHEN 17.
        WA_DATA-RTEXT10 = WA_EXCEL-VALUE .
      WHEN 18.
        WA_DATA-DEPTAPR = WA_EXCEL-VALUE .
      WHEN 19.
        WA_DATA-DEPTH = WA_EXCEL-VALUE .
      WHEN 20.
         IF WA_EXCEL-VALUE IS NOT INITIAL.
          CONCATENATE WA_EXCEL-VALUE+6(4) WA_EXCEL-VALUE+3(2) WA_EXCEL-VALUE+0(2) INTO WA_EXCEL-VALUE .
          WA_DATA-DEPTHDT = WA_EXCEL-VALUE .
        ENDIF.
*         LV_CLEANED_VALUE = WA_EXCEL-VALUE.
*        REPLACE ALL OCCURRENCES OF '-' IN LV_CLEANED_VALUE WITH SPACE .
*        CONDENSE LV_CLEANED_VALUE.
*        WA_DATA-DEPTHDT  = LV_CLEANED_VALUE.
*        CLEAR LV_CLEANED_VALUE.
*        WA_DATA-DEPTHDT = WA_EXCEL-VALUE .
      WHEN 21.
         LV_CLEANED_VALUE = WA_EXCEL-VALUE.
        REPLACE ALL OCCURRENCES OF ':' IN LV_CLEANED_VALUE WITH SPACE .
        CONDENSE LV_CLEANED_VALUE.
        WA_DATA-DEPTHTM  = LV_CLEANED_VALUE.
        CLEAR LV_CLEANED_VALUE.
*        WA_DATA-DEPTHTM = WA_EXCEL-VALUE .
      WHEN 22.
        WA_DATA-DEPTHUNAME = WA_EXCEL-VALUE .
      WHEN 23.
        WA_DATA-QAPERNR = WA_EXCEL-VALUE .
      WHEN 24.
         IF WA_EXCEL-VALUE IS NOT INITIAL.
          CONCATENATE WA_EXCEL-VALUE+6(4) WA_EXCEL-VALUE+3(2) WA_EXCEL-VALUE+0(2) INTO WA_EXCEL-VALUE .
          WA_DATA-QAPPRDT = WA_EXCEL-VALUE .
        ENDIF.
*         LV_CLEANED_VALUE = WA_EXCEL-VALUE.
*        REPLACE ALL OCCURRENCES OF '-' IN LV_CLEANED_VALUE WITH SPACE .
*        CONDENSE LV_CLEANED_VALUE.
*        WA_DATA-QAPPRDT  = LV_CLEANED_VALUE.
*        CLEAR LV_CLEANED_VALUE.
*        WA_DATA-QAPPRDT = WA_EXCEL-VALUE .
      WHEN 25.
         LV_CLEANED_VALUE = WA_EXCEL-VALUE.
        REPLACE ALL OCCURRENCES OF ':' IN LV_CLEANED_VALUE WITH SPACE .
        CONDENSE LV_CLEANED_VALUE.
        WA_DATA-QAPPRTM  = LV_CLEANED_VALUE.
        CLEAR LV_CLEANED_VALUE.
*        WA_DATA-QAPPRTM = WA_EXCEL-VALUE .
      WHEN 26.
        WA_DATA-QAPPRUNAME = WA_EXCEL-VALUE .
      WHEN 27.
        WA_DATA-QADAYS = WA_EXCEL-VALUE .
      WHEN 28.
         IF WA_EXCEL-VALUE IS NOT INITIAL.
          CONCATENATE WA_EXCEL-VALUE+6(4) WA_EXCEL-VALUE+3(2) WA_EXCEL-VALUE+0(2) INTO WA_EXCEL-VALUE .
          WA_DATA-QAREVDT = WA_EXCEL-VALUE .
        ENDIF.
*         LV_CLEANED_VALUE = WA_EXCEL-VALUE.
*        REPLACE ALL OCCURRENCES OF '-' IN LV_CLEANED_VALUE WITH SPACE .
*        CONDENSE LV_CLEANED_VALUE.
*        WA_DATA-QAREVDT  = LV_CLEANED_VALUE.
*        CLEAR LV_CLEANED_VALUE.
*        WA_DATA-QAREVDT = WA_EXCEL-VALUE .
      WHEN 29.
         LV_CLEANED_VALUE = WA_EXCEL-VALUE.
        REPLACE ALL OCCURRENCES OF ':' IN LV_CLEANED_VALUE WITH SPACE .
        CONDENSE LV_CLEANED_VALUE.
        WA_DATA-QAREVTM  = LV_CLEANED_VALUE.
        CLEAR LV_CLEANED_VALUE.
*        WA_DATA-QAREVTM = WA_EXCEL-VALUE .
      WHEN 30.
        WA_DATA-QAREVUNAME = WA_EXCEL-VALUE .
      WHEN 31.
        WA_DATA-QATEXT1 = WA_EXCEL-VALUE .
      WHEN 32.
        WA_DATA-QATEXT2 = WA_EXCEL-VALUE .
      WHEN 33.
        WA_DATA-QATEXT3 = WA_EXCEL-VALUE .
      WHEN 34.
        WA_DATA-QATEXT4 = WA_EXCEL-VALUE .
      WHEN 35.
        WA_DATA-QATEXT5 = WA_EXCEL-VALUE .


    ENDCASE.

    AT END OF ROW.
      WA_DATA-MANDT = SY-MANDT.
      APPEND WA_DATA TO IT_DATA .
*      MODIFY zincvaldata FROM wa_data.
      CLEAR : WA_DATA.
    ENDAT.

  ENDLOOP.
  MODIFY ZDMS5 FROM TABLE IT_DATA.
  IF SY-SUBRC  = 0.
    MESSAGE 'Upload finished. Data inserted/updated into ZDMS5.' TYPE 'S'.
    CLEAR WA_DATA.
    COMMIT WORK.
  ENDIF.
