*&---------------------------------------------------------------------*
*& Report ZDMS1_UPLOAD
*&---------------------------------------------------------------------*
*&
*&---------------------------------------------------------------------*
REPORT ZDMS2_UPLOAD.

TABLES: ZDMS1.

DATA: IT_DATA          TYPE STANDARD TABLE OF ZDMS1,
      WA_DATA          TYPE ZDMS1,
      IT_RAW           TYPE TRUXS_T_TEXT_DATA,
      LV_FILENAME      TYPE RLGRAP-FILENAME,
      LV_CLEANED_VALUE TYPE STRING.
DATA : IT_EXCEL TYPE TABLE OF ALSMEX_TABLINE.
*DATA : wa_excel TYPE alsmex_tabline.

TYPES: BEGIN OF TY_DATA,
         MANDT   TYPE string,
         MJAHR   TYPE STRING,
         MBLNR   TYPE STRING,
         DEPT    TYPE STRING,

         " Date & Time fields changed to STRING
         EBUDAT  TYPE STRING,
         EUZEIT  TYPE STRING,
*         EUZEIT  TYPE UZEIT,

         EUNAME  TYPE STRING,
         EPERNR  TYPE STRING,

         UBUDAT  TYPE STRING,
         UZEIT   TYPE STRING,
*         UZEIT   TYPE UZEIT,

         UNAME   TYPE STRING,
         UPERNR  TYPE STRING,

         APPROVE TYPE STRING,
         REJECT  TYPE STRING,
         NA      TYPE STRING,

         NATEX   TYPE STRING,

         ATEXT1  TYPE STRING,
         TDATE1  TYPE STRING,
         CTDATE1 TYPE STRING,
         REM1    TYPE STRING,
         CTDT1ON TYPE STRING,

         ATEXT2  TYPE STRING,
         TDATE2  TYPE STRING,
         CTDATE2 TYPE STRING,
         REM2    TYPE STRING,
         CTDT2ON TYPE STRING,

         ATEXT3  TYPE STRING,
         TDATE3  TYPE STRING,
         CTDATE3 TYPE STRING,
         REM3    TYPE STRING,
         CTDT3ON TYPE STRING,

         ATEXT4  TYPE STRING,
         TDATE4  TYPE STRING,
         CTDATE4 TYPE STRING,
         REM4    TYPE STRING,
         CTDT4ON TYPE STRING,

         ATEXT5  TYPE STRING,
         TDATE5  TYPE STRING,
         CTDATE5 TYPE STRING,
         REM5    TYPE STRING,
         CTDT5ON TYPE STRING,
       END OF TY_DATA.

DATA : GT_RAW     TYPE TRUXS_T_TEXT_DATA,
       GT_UPLOAD  TYPE TABLE OF ZDMS2,
       GW_UPLOAD  TYPE ZDMS2,
       GT_UPLOAD1 TYPE TABLE OF ZDMS2,
       GW_UPLOAD1 TYPE ZDMS2,
       GT_FILE    TYPE TABLE OF TY_DATA,
       GW_FILE    TYPE TY_DATA.
PARAMETERS: P_FILE TYPE RLGRAP-FILENAME OBLIGATORY.

AT SELECTION-SCREEN ON VALUE-REQUEST FOR P_FILE.
  CALL FUNCTION 'F4_FILENAME'
    EXPORTING
      PROGRAM_NAME  = SYST-CPROG
      DYNPRO_NUMBER = SYST-DYNNR
      FIELD_NAME    = ' '
    IMPORTING
      FILE_NAME     = P_FILE.

START-OF-SELECTION.
  CLEAR gt_file[].
  LV_FILENAME  =  P_FILE.
  BREAK CTPLABAP.
  CALL FUNCTION 'TEXT_CONVERT_XLS_TO_SAP'
    EXPORTING
      I_FIELD_SEPERATOR    = 'X'
      I_LINE_HEADER        = 'X'
      I_TAB_RAW_DATA       = GT_RAW
      I_FILENAME           = LV_FILENAME
    TABLES
      I_TAB_CONVERTED_DATA = GT_FILE[]
    EXCEPTIONS
      CONVERSION_FAILED    = 1
      OTHERS               = 2.


  IF GT_FILE[] IS NOT INITIAL.
    LOOP AT GT_FILE INTO GW_FILE.
      MOVE-CORRESPONDING GW_FILE TO GW_UPLOAD.
      CONCATENATE GW_FILE-EBUDAT+6(4) GW_FILE-EBUDAT+3(2) GW_FILE-EBUDAT+0(2) INTO GW_FILE-EBUDAT .
      GW_UPLOAD-EBUDAT = GW_FILE-EBUDAT .
      CONCATENATE GW_FILE-UBUDAT+6(4) GW_FILE-UBUDAT+3(2) GW_FILE-UBUDAT+0(2) INTO GW_FILE-UBUDAT .
      GW_UPLOAD-UBUDAT = GW_FILE-UBUDAT .

      IF GW_FILE-TDATE1 IS NOT INITIAL.
        CONCATENATE GW_FILE-TDATE1+6(4) GW_FILE-TDATE1+3(2) GW_FILE-TDATE1+0(2) INTO GW_FILE-TDATE1 .
        GW_UPLOAD-TDATE1 = GW_FILE-TDATE1 .
      ENDIF.
      IF GW_FILE-TDATE2 IS NOT INITIAL .
        CONCATENATE GW_FILE-TDATE2+6(4) GW_FILE-TDATE2+3(2) GW_FILE-TDATE2+0(2) INTO GW_FILE-TDATE2 .
        GW_UPLOAD-TDATE2 = GW_FILE-TDATE2 .
      ENDIF.
      IF GW_FILE-TDATE3 IS NOT INITIAL .
        CONCATENATE GW_FILE-TDATE3+6(4) GW_FILE-TDATE3+3(2) GW_FILE-TDATE3+0(2) INTO GW_FILE-TDATE3 .
        GW_UPLOAD-TDATE3 = GW_FILE-TDATE3 .
      ENDIF.
      IF GW_FILE-TDATE4 IS NOT INITIAL .
        CONCATENATE GW_FILE-TDATE4+6(4) GW_FILE-TDATE4+3(2) GW_FILE-TDATE4+0(2) INTO GW_FILE-TDATE4 .
        GW_UPLOAD-TDATE4 = GW_FILE-TDATE4 .
      ENDIF.
      IF GW_FILE-TDATE5 IS NOT INITIAL .
        CONCATENATE GW_FILE-TDATE5+6(4) GW_FILE-TDATE5+3(2) GW_FILE-TDATE5+0(2) INTO GW_FILE-TDATE5 .
        GW_UPLOAD-TDATE5 = GW_FILE-TDATE5 .
      ENDIF.


      IF GW_FILE-CTDATE1 IS NOT INITIAL.
        CONCATENATE GW_FILE-CTDATE1+6(4) GW_FILE-CTDATE1+3(2) GW_FILE-CTDATE1+0(2) INTO GW_FILE-CTDATE1 .
        GW_UPLOAD-CTDATE1 = GW_FILE-CTDATE1 .
      ENDIF.
      IF GW_FILE-CTDATE2 IS NOT INITIAL.
        CONCATENATE GW_FILE-CTDATE2+6(4) GW_FILE-CTDATE2+3(2) GW_FILE-CTDATE2+0(2) INTO GW_FILE-CTDATE2 .
        GW_UPLOAD-CTDATE2 = GW_FILE-CTDATE2 .
      ENDIF.
      IF GW_FILE-CTDATE3 IS NOT INITIAL.
        CONCATENATE GW_FILE-CTDATE3+6(4) GW_FILE-CTDATE3+3(2) GW_FILE-CTDATE3+0(2) INTO GW_FILE-CTDATE3 .
        GW_UPLOAD-CTDATE3 = GW_FILE-CTDATE3 .
      ENDIF.
      IF GW_FILE-CTDATE4 IS NOT INITIAL.
        CONCATENATE GW_FILE-CTDATE4+6(4) GW_FILE-CTDATE4+3(2) GW_FILE-CTDATE4+0(2) INTO GW_FILE-CTDATE4 .
        GW_UPLOAD-CTDATE4 = GW_FILE-CTDATE4 .
      ENDIF.
      IF GW_FILE-CTDATE5 IS NOT INITIAL.
        CONCATENATE GW_FILE-CTDATE5+6(4) GW_FILE-CTDATE5+3(2) GW_FILE-CTDATE5+0(2) INTO GW_FILE-CTDATE5 .
        GW_UPLOAD-CTDATE5 = GW_FILE-CTDATE5 .
      ENDIF.

      IF GW_FILE-CTDT1ON IS NOT INITIAL.
        CONCATENATE GW_FILE-CTDT1ON+6(4) GW_FILE-CTDT1ON+3(2) GW_FILE-CTDT1ON+0(2) INTO GW_FILE-CTDT1ON .
        GW_UPLOAD-CTDT1ON = GW_FILE-CTDT1ON .
      ENDIF.
      IF GW_FILE-CTDT2ON IS NOT INITIAL.
        CONCATENATE GW_FILE-CTDT2ON+6(4) GW_FILE-CTDT2ON+3(2) GW_FILE-CTDT2ON+0(2) INTO GW_FILE-CTDT2ON .
        GW_UPLOAD-CTDT2ON = GW_FILE-CTDT2ON .
      ENDIF.
      IF GW_FILE-CTDT3ON IS NOT INITIAL.
        CONCATENATE GW_FILE-CTDT3ON+6(4) GW_FILE-CTDT3ON+3(2) GW_FILE-CTDT3ON+0(2) INTO GW_FILE-CTDT3ON .
        GW_UPLOAD-CTDT3ON = GW_FILE-CTDT3ON .
      ENDIF.
      IF GW_FILE-CTDT4ON IS NOT INITIAL.
        CONCATENATE GW_FILE-CTDT4ON+6(4) GW_FILE-CTDT4ON+3(2) GW_FILE-CTDT4ON+0(2) INTO GW_FILE-CTDT4ON .
        GW_UPLOAD-CTDT4ON = GW_FILE-CTDT4ON .
      ENDIF.
      IF GW_FILE-CTDT5ON IS NOT INITIAL.
        CONCATENATE GW_FILE-CTDT5ON+6(4) GW_FILE-CTDT5ON+3(2) GW_FILE-CTDT5ON+0(2) INTO GW_FILE-CTDT5ON .
        GW_UPLOAD-CTDT5ON = GW_FILE-CTDT5ON .
      ENDIF.

       IF GW_FILE-EUZEIT IS NOT INITIAL.
*        CONCATENATE GW_FILE-EUZEIT+6(4) GW_FILE-EUZEIT+3(2) GW_FILE-EUZEIT+0(2) INTO GW_FILE-EUZEIT .
*        GW_UPLOAD-EUZEIT = GW_FILE-EUZEIT .
      ENDIF.


      GW_UPLOAD-MANDT = SY-MANDT.
      APPEND GW_UPLOAD TO GT_UPLOAD.
      CLEAR GW_UPLOAD.
    ENDLOOP.
  ENDIF.

  IF GT_UPLOAD[] IS NOT INITIAL.
    MODIFY ZDMS2 FROM TABLE GT_UPLOAD[].
    IF  SY-SUBRC = 0 .
      MESSAGE 'Upload finished. Data inserted/updated into ZDMS2.' TYPE 'S'.
    ENDIF.
  ENDIF.
