*&---------------------------------------------------------------------*
*& Report ZDMS4_UPLOAD
*&---------------------------------------------------------------------*
*&
*&---------------------------------------------------------------------*
REPORT ZDMS4_UPLOAD.

TABLES: ZDMS4.

DATA: IT_DATA          TYPE STANDARD TABLE OF ZDMS4,
      WA_DATA          TYPE ZDMS4,
      IT_RAW           TYPE TRUXS_T_TEXT_DATA,
      LV_FILENAME      TYPE RLGRAP-FILENAME,
      LV_CLEANED_VALUE TYPE STRING.
DATA : IT_EXCEL TYPE TABLE OF ZALSMEX_TABLINE.
*DATA : wa_excel TYPE alsmex_tabline.

PARAMETERS: P_FILE TYPE RLGRAP-FILENAME OBLIGATORY.

AT SELECTION-SCREEN ON VALUE-REQUEST FOR P_FILE.
  CALL FUNCTION 'F4_FILENAME'
    EXPORTING
      PROGRAM_NAME  = SYST-CPROG
      DYNPRO_NUMBER = SYST-DYNNR
      FIELD_NAME    = ' '
    IMPORTING
      FILE_NAME     = P_FILE.

START-OF-SELECTION.
  LV_FILENAME  =  P_FILE.
  BREAK CTPLABAP.
  CALL FUNCTION 'ZALSM_EXCEL_TO_INTERNAL_TABLE'
    EXPORTING
      FILENAME                = LV_FILENAME
      I_BEGIN_COL             = '1'
      I_BEGIN_ROW             = '2'
      I_END_COL               = '99'
      I_END_ROW               = '99999'
    TABLES
      INTERN                  = IT_EXCEL
    EXCEPTIONS
      INCONSISTENT_PARAMETERS = 1
      UPLOAD_OLE              = 2
      OTHERS                  = 3.
  IF SY-SUBRC <> 0.
* Implement suitable error handling here
  ENDIF.


  LOOP AT IT_EXCEL INTO DATA(WA_EXCEL).
    CASE WA_EXCEL-COL.
      WHEN 1.
        WA_DATA-MJAHR =   WA_EXCEL-VALUE.
      WHEN 2.
         WA_DATA-MBLNR  = WA_EXCEL-VALUE.
        CALL FUNCTION 'CONVERSION_EXIT_ALPHA_INPUT'
          EXPORTING
            INPUT         =  WA_DATA-MBLNR
         IMPORTING
           OUTPUT        =  WA_DATA-MBLNR
                  .
      WHEN 3.
        WA_DATA-WERKS = WA_EXCEL-VALUE  .
      WHEN 4.
        WA_DATA-PERNR = WA_EXCEL-VALUE .
      WHEN 5.
         IF WA_EXCEL-VALUE IS NOT INITIAL.
          CONCATENATE WA_EXCEL-VALUE+6(4) WA_EXCEL-VALUE+3(2) WA_EXCEL-VALUE+0(2) INTO WA_EXCEL-VALUE .
          WA_DATA-BUDAT = WA_EXCEL-VALUE .
        ENDIF.
*         LV_CLEANED_VALUE = WA_EXCEL-VALUE.
*        REPLACE ALL OCCURRENCES OF '-' IN LV_CLEANED_VALUE WITH SPACE .
*        CONDENSE LV_CLEANED_VALUE.
*        WA_DATA-BUDAT  = LV_CLEANED_VALUE.
*        CLEAR LV_CLEANED_VALUE.
*        WA_DATA-BUDAT = WA_EXCEL-VALUE .
      WHEN 6.
         LV_CLEANED_VALUE = WA_EXCEL-VALUE.
        REPLACE ALL OCCURRENCES OF ':' IN LV_CLEANED_VALUE WITH SPACE .
        CONDENSE LV_CLEANED_VALUE.
        WA_DATA-UZEIT  = LV_CLEANED_VALUE.
        CLEAR LV_CLEANED_VALUE.
*        WA_DATA-UZEIT = WA_EXCEL-VALUE .
      WHEN 7.
        WA_DATA-UNAME = WA_EXCEL-VALUE .
      WHEN 8.
        WA_DATA-RPN_S = WA_EXCEL-VALUE .
      WHEN 9.
        WA_DATA-RPN_P = WA_EXCEL-VALUE .
      WHEN 10.
        WA_DATA-RPN_D = WA_EXCEL-VALUE .
      WHEN 11.
        WA_DATA-RTEXT1 = WA_EXCEL-VALUE .
      WHEN 12.
        WA_DATA-RTEXT2 = WA_EXCEL-VALUE .
      WHEN 13.
        WA_DATA-RTEXT3 = WA_EXCEL-VALUE .
      WHEN 14.
        WA_DATA-CHGTYPN = WA_EXCEL-VALUE .
      WHEN 15.
        WA_DATA-CHGTYPM = WA_EXCEL-VALUE .
      WHEN 16.
        WA_DATA-QHREM = WA_EXCEL-VALUE .
      WHEN 17.
        WA_DATA-QHAPPROVE = WA_EXCEL-VALUE .
      WHEN 18.
        WA_DATA-QHREJECT = WA_EXCEL-VALUE .
      WHEN 19.
        WA_DATA-QHPERNR = WA_EXCEL-VALUE .
      WHEN 20.
        IF WA_EXCEL-VALUE IS NOT INITIAL.
          CONCATENATE WA_EXCEL-VALUE+6(4) WA_EXCEL-VALUE+3(2) WA_EXCEL-VALUE+0(2) INTO WA_EXCEL-VALUE .
          WA_DATA-QHDATE = WA_EXCEL-VALUE .
        ENDIF.
*         LV_CLEANED_VALUE = WA_EXCEL-VALUE.
*        REPLACE ALL OCCURRENCES OF '-' IN LV_CLEANED_VALUE WITH SPACE .
*        CONDENSE LV_CLEANED_VALUE.
*        WA_DATA-QHDATE  = LV_CLEANED_VALUE.
*        CLEAR LV_CLEANED_VALUE.
*        WA_DATA-QHDATE = WA_EXCEL-VALUE .
      WHEN 21.
         LV_CLEANED_VALUE = WA_EXCEL-VALUE.
        REPLACE ALL OCCURRENCES OF ':' IN LV_CLEANED_VALUE WITH SPACE .
        CONDENSE LV_CLEANED_VALUE.
        WA_DATA-QHUZEIT  = LV_CLEANED_VALUE.
        CLEAR LV_CLEANED_VALUE.
*        WA_DATA-QHUZEIT = WA_EXCEL-VALUE .
      WHEN 22.
        WA_DATA-QHUNAME = WA_EXCEL-VALUE .
      WHEN 23.
        WA_DATA-CCNUMB = WA_EXCEL-VALUE .
      WHEN 24.
        WA_DATA-CCNUMB1 = WA_EXCEL-VALUE .
      WHEN 25.
        WA_DATA-QAMJAHR = WA_EXCEL-VALUE .
      WHEN 26.
        WA_DATA-TDREM = WA_EXCEL-VALUE .
      WHEN 27.
        WA_DATA-TDREM1 = WA_EXCEL-VALUE .
      WHEN 28.
        WA_DATA-TDREM2 = WA_EXCEL-VALUE .
      WHEN 29.
        WA_DATA-TDAPPROVE = WA_EXCEL-VALUE .
      WHEN 30.
        WA_DATA-TDREJECT = WA_EXCEL-VALUE .
      WHEN 31.
        WA_DATA-TDPERNR = WA_EXCEL-VALUE .
      WHEN 32.
        IF WA_EXCEL-VALUE IS NOT INITIAL.
          CONCATENATE WA_EXCEL-VALUE+6(4) WA_EXCEL-VALUE+3(2) WA_EXCEL-VALUE+0(2) INTO WA_EXCEL-VALUE .
          WA_DATA-TDDATE = WA_EXCEL-VALUE .
        ENDIF.
         LV_CLEANED_VALUE = WA_EXCEL-VALUE.
        REPLACE ALL OCCURRENCES OF '-' IN LV_CLEANED_VALUE WITH SPACE .
        CONDENSE LV_CLEANED_VALUE.
        WA_DATA-TDDATE  = LV_CLEANED_VALUE.
        CLEAR LV_CLEANED_VALUE.
*        WA_DATA-TDDATE = WA_EXCEL-VALUE .
      WHEN 33.
         LV_CLEANED_VALUE = WA_EXCEL-VALUE.
        REPLACE ALL OCCURRENCES OF ':' IN LV_CLEANED_VALUE WITH SPACE .
        CONDENSE LV_CLEANED_VALUE.
        WA_DATA-TDUZEIT  = LV_CLEANED_VALUE.
        CLEAR LV_CLEANED_VALUE.
*        WA_DATA-TDUZEIT = WA_EXCEL-VALUE .
      WHEN 34.
        WA_DATA-TDUNAME = WA_EXCEL-VALUE .
      WHEN 35.
        WA_DATA-CL1 = WA_EXCEL-VALUE .
      WHEN 36.
        WA_DATA-CL1PERNR = WA_EXCEL-VALUE .
      WHEN 37.
        IF WA_EXCEL-VALUE IS NOT INITIAL.
          CONCATENATE WA_EXCEL-VALUE+6(4) WA_EXCEL-VALUE+3(2) WA_EXCEL-VALUE+0(2) INTO WA_EXCEL-VALUE .
          WA_DATA-CL1DATE = WA_EXCEL-VALUE .
        ENDIF.
*         LV_CLEANED_VALUE = WA_EXCEL-VALUE.
*        REPLACE ALL OCCURRENCES OF '-' IN LV_CLEANED_VALUE WITH SPACE .
*        CONDENSE LV_CLEANED_VALUE.
*        WA_DATA-CL1DATE  = LV_CLEANED_VALUE.
*        CLEAR LV_CLEANED_VALUE.
*        WA_DATA-CL1DATE = WA_EXCEL-VALUE .
      WHEN 38.
         LV_CLEANED_VALUE = WA_EXCEL-VALUE.
        REPLACE ALL OCCURRENCES OF ':' IN LV_CLEANED_VALUE WITH SPACE .
        CONDENSE LV_CLEANED_VALUE.
        WA_DATA-CL1UZEIT  = LV_CLEANED_VALUE.
        CLEAR LV_CLEANED_VALUE.
*        WA_DATA-CL1UZEIT = WA_EXCEL-VALUE .
      WHEN 39.
        WA_DATA-CL1UNAME = WA_EXCEL-VALUE .
      WHEN 40.
        WA_DATA-CL1TXT1 = WA_EXCEL-VALUE .
      WHEN 41.
        WA_DATA-CL1TXT2 = WA_EXCEL-VALUE .
      WHEN 42.
        WA_DATA-CL1TXT3 = WA_EXCEL-VALUE .
      WHEN 43.
        WA_DATA-QHCL1 = WA_EXCEL-VALUE .
      WHEN 44.
        WA_DATA-QHCL1PERNR = WA_EXCEL-VALUE .
      WHEN 45.
        IF WA_EXCEL-VALUE IS NOT INITIAL.
          CONCATENATE WA_EXCEL-VALUE+6(4) WA_EXCEL-VALUE+3(2) WA_EXCEL-VALUE+0(2) INTO WA_EXCEL-VALUE .
          WA_DATA-QHCL1DATE = WA_EXCEL-VALUE .
        ENDIF.
*         LV_CLEANED_VALUE = WA_EXCEL-VALUE.
*        REPLACE ALL OCCURRENCES OF '-' IN LV_CLEANED_VALUE WITH SPACE .
*        CONDENSE LV_CLEANED_VALUE.
*        WA_DATA-QHCL1DATE  = LV_CLEANED_VALUE.
*        CLEAR LV_CLEANED_VALUE.
*        WA_DATA-QHCL1DATE = WA_EXCEL-VALUE .
      WHEN 46.
         LV_CLEANED_VALUE = WA_EXCEL-VALUE.
        REPLACE ALL OCCURRENCES OF ':' IN LV_CLEANED_VALUE WITH SPACE .
        CONDENSE LV_CLEANED_VALUE.
        WA_DATA-QHCL1UZEIT  = LV_CLEANED_VALUE.
        CLEAR LV_CLEANED_VALUE.
*        WA_DATA-QHCL1UZEIT = WA_EXCEL-VALUE .
      WHEN 47.
        WA_DATA-QHCL1UNAME = WA_EXCEL-VALUE .
      WHEN 48.
        WA_DATA-CL2 = WA_EXCEL-VALUE .
      WHEN 49.
        WA_DATA-CL2PERNR = WA_EXCEL-VALUE .
      WHEN 50.
        IF WA_EXCEL-VALUE IS NOT INITIAL.
          CONCATENATE WA_EXCEL-VALUE+6(4) WA_EXCEL-VALUE+3(2) WA_EXCEL-VALUE+0(2) INTO WA_EXCEL-VALUE .
          WA_DATA-CL2DATE = WA_EXCEL-VALUE .
        ENDIF.
*         LV_CLEANED_VALUE = WA_EXCEL-VALUE.
*        REPLACE ALL OCCURRENCES OF '-' IN LV_CLEANED_VALUE WITH SPACE .
*        CONDENSE LV_CLEANED_VALUE.
*        WA_DATA-CL2DATE  = LV_CLEANED_VALUE.
*        CLEAR LV_CLEANED_VALUE.
*        WA_DATA-CL2DATE = WA_EXCEL-VALUE .
      WHEN 51.
         LV_CLEANED_VALUE = WA_EXCEL-VALUE.
        REPLACE ALL OCCURRENCES OF ':' IN LV_CLEANED_VALUE WITH SPACE .
        CONDENSE LV_CLEANED_VALUE.
        WA_DATA-CL2UZEIT  = LV_CLEANED_VALUE.
        CLEAR LV_CLEANED_VALUE.
*        WA_DATA-CL2UZEIT = WA_EXCEL-VALUE .
      WHEN 52.
        WA_DATA-CL2UNAME = WA_EXCEL-VALUE .
      WHEN 53.
        WA_DATA-CL2TXT1 = WA_EXCEL-VALUE .
      WHEN 54.
        WA_DATA-CL2TXT2 = WA_EXCEL-VALUE .
      WHEN 55.
        WA_DATA-CL2TXT3 = WA_EXCEL-VALUE .
      WHEN 56.
        WA_DATA-QHCL2 = WA_EXCEL-VALUE .
      WHEN 57.
        WA_DATA-QHCL2PERNR = WA_EXCEL-VALUE .
      WHEN 58.
         IF WA_EXCEL-VALUE IS NOT INITIAL.
          CONCATENATE WA_EXCEL-VALUE+6(4) WA_EXCEL-VALUE+3(2) WA_EXCEL-VALUE+0(2) INTO WA_EXCEL-VALUE .
          WA_DATA-QHCL2DATE = WA_EXCEL-VALUE .
        ENDIF.
*         LV_CLEANED_VALUE = WA_EXCEL-VALUE.
*        REPLACE ALL OCCURRENCES OF '-' IN LV_CLEANED_VALUE WITH SPACE .
*        CONDENSE LV_CLEANED_VALUE.
*        WA_DATA-QHCL2DATE  = LV_CLEANED_VALUE.
*        CLEAR LV_CLEANED_VALUE.
**        WA_DATA-QHCL2DATE = WA_EXCEL-VALUE .
      WHEN 59.
         LV_CLEANED_VALUE = WA_EXCEL-VALUE.
        REPLACE ALL OCCURRENCES OF ':' IN LV_CLEANED_VALUE WITH SPACE .
        CONDENSE LV_CLEANED_VALUE.
        WA_DATA-QHCL2UZEIT  = LV_CLEANED_VALUE.
        CLEAR LV_CLEANED_VALUE.
*        WA_DATA-QHCL2UZEIT = WA_EXCEL-VALUE .
      WHEN 60.
        WA_DATA-QHCL2UNAME = WA_EXCEL-VALUE .
      WHEN 61.
         IF WA_EXCEL-VALUE IS NOT INITIAL.
          CONCATENATE WA_EXCEL-VALUE+6(4) WA_EXCEL-VALUE+3(2) WA_EXCEL-VALUE+0(2) INTO WA_EXCEL-VALUE .
          WA_DATA-TCLOSEDT = WA_EXCEL-VALUE .
        ENDIF.
*         LV_CLEANED_VALUE = WA_EXCEL-VALUE.
*        REPLACE ALL OCCURRENCES OF '-' IN LV_CLEANED_VALUE WITH SPACE .
*        CONDENSE LV_CLEANED_VALUE.
*        WA_DATA-TCLOSEDT  = LV_CLEANED_VALUE.
*        CLEAR LV_CLEANED_VALUE.
*        WA_DATA-TCLOSEDT = WA_EXCEL-VALUE .
      WHEN 62.
        WA_DATA-TCLOSEDTBY = WA_EXCEL-VALUE .
      WHEN 63.
         IF WA_EXCEL-VALUE IS NOT INITIAL.
          CONCATENATE WA_EXCEL-VALUE+6(4) WA_EXCEL-VALUE+3(2) WA_EXCEL-VALUE+0(2) INTO WA_EXCEL-VALUE .
          WA_DATA-TCLOSEDTON = WA_EXCEL-VALUE .
        ENDIF.
*          LV_CLEANED_VALUE = WA_EXCEL-VALUE.
*        REPLACE ALL OCCURRENCES OF '-' IN LV_CLEANED_VALUE WITH SPACE .
*        CONDENSE LV_CLEANED_VALUE.
*        WA_DATA-TCLOSEDTON  = LV_CLEANED_VALUE.
*        CLEAR LV_CLEANED_VALUE.
*        WA_DATA-TCLOSEDTON = WA_EXCEL-VALUE .
      WHEN 64.
          LV_CLEANED_VALUE = WA_EXCEL-VALUE.
        REPLACE ALL OCCURRENCES OF ':' IN LV_CLEANED_VALUE WITH SPACE .
        CONDENSE LV_CLEANED_VALUE.
        WA_DATA-TCLOSETMON  = LV_CLEANED_VALUE.
        CLEAR LV_CLEANED_VALUE.
*        WA_DATA-TCLOSETMON = WA_EXCEL-VALUE .
      WHEN 65.
        WA_DATA-TCLOSEUNAME = WA_EXCEL-VALUE .

    ENDCASE.

    AT END OF ROW.
      WA_DATA-MANDT = SY-MANDT.
      APPEND WA_DATA TO IT_DATA .
*      MODIFY zincvaldata FROM wa_data.
      CLEAR : WA_DATA.
    ENDAT.

  ENDLOOP.
  MODIFY ZDMS4 FROM TABLE IT_DATA.
  IF SY-SUBRC  = 0.
    MESSAGE 'Upload finished. Data inserted/updated into ZDMS4.' TYPE 'S'.
    CLEAR WA_DATA.
    COMMIT WORK.
  ENDIF.
